### ISSUE TITLE
[META][AutoDiff] Fix autodiff for classes and class-valued arguments

### ISSUE THREAD

**Issue by asl** [apple/swift#65012]
This is a meta-issue noting all kinds of issues related to differentiating of classes, class methods, etc. While the things are more or less working for ordinary functions and structs, there are lots of missed functionality related to classes.

* Classes-type function arguments have reference semantics. Therefore they should be treated semantically similar to inout arguments for, however, there are lots of differences. In particular, we need to fix activity analysis for classes, determination of semantic results, etc.
* There are lots of interesting special things around classes including e.g. accessors. Setters work by a chance (however, the activity analysis in anything involving setters is just plain wrong), and we do not support `read / modify` accessors.
* To support `read / modify` accessors we need to implement missed pieces of functionality around differentiation of co-routines. While semantically it is unclear how one could derive a derivative of function that essentially might return different values in general, we can narrow down task to support only `@yield_once` co-routines, where everything essentially returns only once, there is no way to `resume / abort` co-routine, so they act as a normal functions and ``@yield_once` is just a way to transfer ownership.

Related issues:

- [ ] https://github.com/apple/swift/issues/54685
- [ ] https://github.com/apple/swift/issues/55542
- [ ] https://github.com/apple/swift/issues/54404

**Comment by asl** [comment]
Tagging @rxwei @dan-zheng @BradLarson

**Comment by asl** [comment]
This is for @BradLarson :)

**Comment by rxwei** [comment]
I second Dan's quick check. It seems that there are more important issues to tackle to bring us closer to Swift Evolution like ABI stability.
