### ISSUE TITLE
☂️ Tracking issue for C++ interoperability fixes we want for Swift-5.9

### ISSUE THREAD

**Issue by hyp** [apple/swift#65808]
# Must-fixes for Swift-5.9

This section tracks all of the C++ interoperability fixes we would like to have in the Swift-5.9 release.
They're categorized by different groups presented below:

## "Forward" interop - using C++ APIs in Swift

- [x] https://github.com/apple/swift/issues/61929
- [x] https://github.com/apple/swift/issues/64401
- [x] https://github.com/apple/swift/issues/65710
- [x] https://github.com/apple/swift/issues/65891
- [x] https://github.com/apple/swift/issues/65918
- [x] https://github.com/apple/swift/issues/66322
- [x] https://github.com/apple/swift/issues/66323
- [x] https://github.com/apple/swift/issues/61454
- [x] https://github.com/apple/swift/issues/66501
- [x] https://github.com/apple/swift/issues/66523
- [x] https://github.com/apple/swift/issues/67410

## "Reverse" interop - using Swift APIs in C++

- [x] https://github.com/apple/swift/issues/66324
- [x] https://github.com/apple/swift/issues/63452

## Build / platform-specific fixes

- [x] https://github.com/apple/swift/issues/63446
- [x] https://github.com/apple/swift/issues/66326
- [x] windows: test C++ stdlib support
- [x] https://github.com/apple/swift/issues/64457 (linux & libstdc++)

## SwiftPM usability

Compiler support for `@_implementationOnly` imports:
- [x] https://github.com/apple/swift/issues/65831

Improved diagnostics when importing things requiring C++ interop:
- [x] https://github.com/apple/swift/issues/65833
- [x] https://github.com/apple/swift/issues/65832

SwiftPM fixes:
- [x] https://github.com/apple/swift-package-manager/issues/6565

## Interop ecosystem - IDE, tooling support, debugging

- [ ] indexing-related: https://github.com/apple/swift/issues/65646

**Comment by hyp** [comment]
We're done with 5.9, closing.
I will open a follow-up issue for tracking 5.9.X fixes.
